### ISSUE TITLE
Taking parametric interval linear system seriuosly

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/IntervalLinearAlgebra.jl#99]
Normal interval linear systems (that is the main functionality of this package currently) are quite useless. In most (prob. all) true applications, you have parametric interval linear systems (PILS, like the beer 🍺 ), that is a system of the form

```
A(p)x = b(p)
```

where `p` is a vector of intervals (ranges for each parameters). Treating PILS like normal linear systems gives poor results, because dependency problem etc. the next big milestone of this package is to take parametric interval linear systems seriously and produce a state-of-the-art toolset for it. This would greatly increase uniqueness and value of the package. This metaissue collects  different scenarios and references related to PILS.

### Symmetric systems

- [ ] Interval linear systems with symmetric matrices, skew-symmetric matrices and dependencies in the right hand side (this could be a good starting point to get the ball rolling)

### Linear/Affine dependency on the parameters

- I. Skalna, A Method for Outer Interval Solution of Systems of Linear Equations Depending Linearly on Interval Parameters, Reliable Computing, Volume 12, Number 2, April, 2006, pp. 107–120
- Popova, E. D. (2004). Parametric interval linear solver. Numerical Algorithms, 37(1), 345-356.
- Skalna, I., & Hladík, M. (2017). A new method for computing a p-solution to parametric interval linear systems with affine-linear and nonlinear dependencies. BIT Numerical Mathematics, 57(4), 1109-1136.
- Hladík, M. (2012). Enclosures for the solution set of parametric interval linear systems. International Journal of Applied Mathematics and Computer Science, 22, 561-574.
- Popova, E., & Krämer, W. (2007). Inner and outer bounds for the solution set of parametric linear systems. Journal of Computational and Applied Mathematics, 199(2), 310-316.
- Skalna, I., & Hladík, M. (2021). On preconditioning and solving an extended class of interval parametric linear systems. Numerical Algorithms, 87(4), 1535-1562.

### Nonlinear dependency

- Skalna, I. (2009, September). Direct method for solving parametric interval linear systems with non-affine dependencies. In International conference on parallel processing and applied mathematics (pp. 485-494). Springer, Berlin, Heidelberg.
- Skalna, I. (2009, September). A global optimization method for solving parametric linear systems whose input data are rational functions of interval parameters. In International Conference on Parallel Processing and Applied Mathematics (pp. 475-484). Springer, Berlin, Heidelberg.
### Applications

- [ ] FEM: once a good solver for parametric interval linear systems is available, in principle interval FEM is just replacing `A\b` by the PILS solver, a linear-affine PILS solver could already be enough for a good amount of applications
- [ ] Electric circuits. When solving resistive electrical circuits with e.g. nodal / mesh /modified nodal analysis, the problem is to solve a linear systems that depends linearly on resistances or conductances, hence linear PILS could be a good tool for circuit analysis with uncertainty in parameters. This can also generalize to AC RLC-circuits, as one obtains a linear system with linear dependency on impedances or admittances, which are complex numbers, but a general complex linear system can be rewritten as two linear PILS, hence the final system would still be linear-PILS.
- [ ] Complex ILS. A complex interval linear system can be rewritten as two real ILS with linear dependency.
- [ ] Least squares, the linear leastsquare solution of an overdetermined ILS can be found by solving a symmetric ILS.

### Data structure / interface

Let us first focus on symmetric and linear PILS. In a linear PILS we have

```
A(p) = A0 + A1*p1 + A2*p2 + .... + An*pn
```

- [ ] think of interface / dastructures to handle linear-PILS

cc @mforets @dpsanders @schillic @jorgepz

**Comment by jorgepz** [comment]
Great definitions! A small comment to reinforce the FEM application: in linear static analyses, the FEM matrix is symmetric and sparse! If we consider the young moduli of all the elements (`pi`) as interval parameters, then the matrix `A0` would be null. On the other hand, if we assume some of the young moduli to be known or fixed, then the matrix `A0` would be nonzero... Chapter 3 from [Bathe's book](http://web.mit.edu/kjb/www/Books/FEP_2nd_Edition_4th_Printing.pdf) is a good reference.
